language: go

install: true

go:
  - "1.10"

before_install:
  - go get -u github.com/golang/dep/...
  - dep ensure
  - go get -v github.com/golang/lint/golint
  - go get -v github.com/mmcdole/gofeed

script:
  - cd test && go test
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - go vet $(go list ./... | grep -v "/vendor/")
