language: go

install: true

go:
  - "1.10"

before_install:
  - go get -u github.com/golang/dep/...
  - dep ensure
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter ./... --vendor
  - cd test && go test
  - go test -v -race $(go list ./... | grep -v "/vendor/")

deploy:
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.10\.[0-9]+$
